// Mock Data
export const mockProducts = [
  {
    id: 1,
    title: "Product Name",
    description: "High-quality wireless headphones with noise cancellation",
    price: 299,
    image: "/api/placeholder/300/300",
    rating: 5,
    category: "Electronics",
    location: "New York",
    isNew: true,
  },
  {
    id: 2,
    title: "Product Name",
    description: "Advanced fitness tracking and notifications",
    price: 399,
    image: "/api/placeholder/300/300",
    rating: 4,
    category: "Electronics",
    location: "California",
    isNew: false,
  },
  {
    id: 3,
    title: "Product Name",
    description: "Genuine leather jacket with modern design",
    price: 199,
    image: "/api/placeholder/300/300",
    rating: 4,
    category: "Fashion",
    location: "Texas",
    isNew: true,
  },
  {
    id: 4,
    title: "Coffee Maker",
    description: "Professional grade espresso machine",
    price: 599,
    image: "/api/placeholder/300/300",
    rating: 5,
    category: "Home",
    location: "Florida",
    isNew: false,
  },
  {
    id: 5,
    title: "Gaming Mouse",
    description: "Precision gaming mouse with RGB lighting",
    price: 79,
    image: "/api/placeholder/300/300",
    rating: 4,
    category: "Electronics",
    location: "Washington",
    isNew: true,
  },
  {
    id: 6,
    title: "Yoga Mat",
    description: "Non-slip premium yoga mat for all exercises",
    price: 49,
    image: "/api/placeholder/300/300",
    rating: 3,
    category: "Sports",
    location: "Oregon",
    isNew: false,
  },
  {
    id: 7,
    title: "Smartphone Case",
    description: "Protective case with wireless charging support",
    price: 29,
    image: "/api/placeholder/300/300",
    rating: 4,
    category: "Electronics",
    location: "Nevada",
    isNew: true,
  },
  {
    id: 8,
    title: "Running Shoes",
    description: "Lightweight running shoes for maximum comfort",
    price: 129,
    image: "/api/placeholder/300/300",
    rating: 5,
    category: "Sports",
    location: "Colorado",
    isNew: false,
  },
  {
    id: 9,
    title: "Desk Lamp",
    description: "LED desk lamp with adjustable brightness",
    price: 89,
    image: "/api/placeholder/300/300",
    rating: 4,
    category: "Home",
    location: "Utah",
    isNew: true,
  },
  {
    id: 10,
    title: "Backpack",
    description: "Durable travel backpack with laptop compartment",
    price: 159,
    image: "/api/placeholder/300/300",
    rating: 5,
    category: "Fashion",
    location: "Arizona",
    isNew: false,
  },
  {
    id: 11,
    title: "Bluetooth Speaker",
    description: "Portable speaker with deep bass and long battery",
    price: 119,
    image: "/api/placeholder/300/300",
    rating: 4,
    category: "Electronics",
    location: "Michigan",
    isNew: true,
  },
  {
    id: 12,
    title: "Kitchen Knife Set",
    description: "Professional chef knife set with wooden block",
    price: 249,
    image: "/api/placeholder/300/300",
    rating: 5,
    category: "Home",
    location: "Illinois",
    isNew: false,
  },
];

export const heroSlides = [
  {
    id: 1,
    title: "Summer Collection",
    description: "Discover our latest summer arrivals",
    image: "/api/placeholder/1200/400",
  },
  {
    id: 2,
    title: "Tech Deals",
    description: "Amazing discounts on electronics",
    image: "/api/placeholder/1200/400",
  },
  {
    id: 3,
    title: "Home Essentials",
    description: "Everything you need for your home",
    image: "/api/placeholder/1200/400",
  },
];